### ISSUE TITLE
Server nginx config

### ISSUE THREAD

**Issue by samox1n** [docpad/docpad#1023]
What to write in server config?

nginx
node 0.10.25
npm 2.12.0
docpad 6.78.4

Way to docpad: /var/www/doc.ixley.ru/

Thx

**Comment by mikeumus** [comment]
Hey @samox1n, 
 
 When you say server config, you mean nginx's server config I assume? 

Hey ixley, and you followed step 5 with setting the docpad port to 80 on [Step 5 of the DocPad DO Tutorial](https://www.digitalocean.com/community/tutorials/how-to-deploy-a-docpad-application-on-ubuntu-14-04) you used? 

You will need to add the following line to your docpad.coffee config file so that DocPad will run your application on port 80. First, open the file for editing:

`nano ~/docpad_test/docpad.coffee`
Add the line `port: 80` within the `docpadConfig = {}` block. The port line needs to be on the first level within the block. You can add it as the first line after docpadConfig = {.

    docpadConfig = {
    
    . . .
    
        port: 80
    
    . . .
    
    }

_ _ _ 

I'd then suggest leaving out the custom port and setting the nginx config to `listen 9778;` and try running that.

**Comment by balupton** [comment]
Closing due to age.
