### ISSUE TITLE
Support on/off in config settings

### ISSUE THREAD

**Issue by blitmap** [docpad/docpad#1031]
Hi, I was looking through Docpad's source and I noticed this:

https://github.com/docpad/docpad/blob/master/src/bin/docpad-compile.coffee#L46

I thought it might be useful to let Docpad's team know that Coffeescript supports `true`, `yes`, `on` which compiles to Javascript's `true` and `false`, `no`, `off` for `false`.

This part of Docpad's source seemed to be emulating that, but it lacks `on` and `off`.  There might be other instances like this in Docpad..

Anyway, toodles :-)

**Comment by balupton** [comment]
Hey, thanks for raising this. I believe there should probably be a comment there to address why this is.

The particular code is checking for string values of `"yes"` and `"no"` - which of course when compiled remain remain strings, rather than being replaced with the booleans `true` and `false`. I believe this particular code here is for compatibility with whatever input system we were using, rather than any particular end-user feature.

**Comment by balupton** [comment]
Replaced by https://github.com/docpad/docpad/issues/1046
