### ISSUE TITLE
What would you pay for?

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#633]
If we could whip up some premium services, or features, or bounties, or anything *within the month*. What would you put your money down for?

Perhaps on one of these?

- Premium/priority support
- Plugin development
- DocPad customisation
- Training
- New Documentation
- Prioritized issues

Or something else? If so, any ideas how much and what for?

**Comment by permadesign** [comment]
I would happily pay for a comprehensive training video going through setting up a Docpad site for a 'typical' client site. With a lot of open-source tools it seems there's a bit of a gulf between 'hello world' documentation and actual training to enable me to use it on a client's site, which is understandable. Something like the videos DevTips did for their Jekyll site, and it would be great for it to be available as an .epub or .mobi as well.

A video showing how to setup, integrate a framework like Bootstrap/Foundation/Polymer, and integrate the inlineGUI would be immensely helpful.

When get that workflow going smoothly I will talk at meetups in Bristol about using Docpad for client sites.

**Comment by mikeumus** [comment]
Awesome @permadesign. A friend and I we're actually considering doing a Udemy for DocPad. This is something I've been wanting to do. I'm sure some of the team can get together and do some Google Hangouts on Air and release those. 

@Greduan, @balupton, @balupton, @ahdinosaur, @RobLoach ! :smile:

**Comment by permadesign** [comment]
Sounds great!

**Comment by mikeumus** [comment]
It does! :notes::ear:

@permadesign, if you don't mind me asking, what brought you to DocPad? :smiley:

**Comment by permadesign** [comment]
Well I was wrangling with WordPress, bumped into all of the standard frustrations there. I've used the Squarespace developer's platform a fair bit and liked that JS templating/Git is supported, but it is only available on their midrange price plan, which means that my clients then have to pay fairly high hosting on which I make no profit. They also have arbitrary limits on the amount of pages/store items you can have before going into a higher payment bracket. My clients really loved the simple admin interface though, way more so than WordPress, which distracted/intimidated them.

I started looking into static site generators, trying to find something which matched the following criteria (this bit is from a blog post I haven't yet finished!):

- an open-source stack with an enthusiatic and active community around it.
- the ability to manage hosting of sites myself, giving no monthly profit to a CMS provider (as is the case with the Squarespace Developer Platform, which I use mainly for its client-friendly admin panel).
- version control being simple to integrate.
- the ability to develop locally with tools like Gulp, File Optimizer, Stylus and Prepros.
- there should be no code-bloat in the CMS, no collossal learning-curve in developing with the CMS, and it should be easily customisable for the needs of each client.
- total control over the optimisation and concatenation of the files which are delivered from server to client.
- a minimal, beautiful admin interface for non-technical clients. I have spent countless un-billable hours training and re-training clients in using WordPress to update their blog, or change a simple line of text on their site. I often receive calls from clients asking whether they need to worry about popups telling them to contact the system administrator about an update, or fixing clients' sites when they've inadvertently added inline styles to a blog post after copying and pasting from Word to WordPress. Ideally, clients should be able to log in, click on the text on the front-end of their site and change it right there.

I was just searching for static site generators and specifically ones using node. To be honest I was more drawn to Wintersmith and CMSs using MongoDB like Apostrophe2 or Buckets, but that was just because I liked the design of their site more than DocPad's. I also liked Roots.cx as it fit my workflow well, but then I kept hearing about DocPad in my searches and looked more into it. I like the vision for it and it has a strong community, and the InlineGUI was the missing part of the puzzle, so I really want to invest time into it.

I found Development Seed's articles about Prose.io and Jekyll very inspiring but I'm just not into Ruby, and the community around DocPad seems more my kind of thing.

**Comment by permadesign** [comment]
More concisely, maybe if you guys put some time into step-by-step video tutorials showing specific use-cases and how it could make people's life way easier than WordPress, and then charge for those tutorials, that might be a good way to make money from it? Like a basic Team Treehouse but just for DocPad.

**Comment by mikeumus** [comment]
Thanks for that full response. I actually had an almost identical path to DocPad. Was in the trenches delivering Wordpress websites to small business clients. 

Charging for the videos wouldn't benefit the community in my opinion. A DocPad PaaS or a successful DocPad consultancy that contributes back are the ideal ways to monetize DocPad from my perspective (or ideally, both).

**Comment by SteveMcArthur** [comment]
I'm with @mikeumus, charging for videos wouldn't benefit the community. We don't want to make it difficult for developers to adopt DocPad. I think the key is enterprise organisations and getting them to either pay a licence fee (maybe controversial) or premium support. A lot of enterprise organisations will not adopt a technology unless they have a formal (and paid for) arrangement of some sort. It just doesn't fit into their buying practices.

**Comment by mikeumus** [comment]
Good idea Steve. Anybody have any such connections?

**Comment by balupton** [comment]
So we've had our [premium support page](http://docpad.org/docs/support) up for a while - I think I've been contacted 5 times since DocPad was created, and 3/5 of those followed through to something - there's been more, but we've forwarded them onto other people.

**Comment by SteveMcArthur** [comment]
@balupton What I was really thinking was charging a licence fee for commercial organisations (part of which would be premium support). $5,000 per year might not be an unusual amount. If you had 10 clients worldwide that would maybe pay for someone to work on docpad full time. If you have 50 clients worldwide then you have a good business. But I'm thinking of docpad as a CMS rather than a blog engine. I'm not sure if there are any enterprise businesses using docpad.

I've been in the situation in a enterprise organisation where we have had to buy a propriety CMS when there where better open source solutions only because the propriety solution has a formal buying arrangement that the organisation can understand.

**Comment by balupton** [comment]
Closing due to age. Further discussion probably should go through the new channels for such things:
https://github.com/docpad/docpad/blob/master/CONTRIBUTING.md
