### ISSUE TITLE
2015 Roadmap

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#927]
I've completed my breakdown of 2014, and will be spending 2015 getting things in order - especially the next 6 months while I complete my final delayed unit of my Bc.S. Computer Science (Information Technology) degree at Curtin University, WA.

The long-term goals for this year are:

## Shutdown Bevry the Business,<br/>Continue Bevry the Community

I have yet to find an accountant that is able to handle the sporadic and often quiet nature of Bevry while being able to answer questions in a timely manner. As such, paying $210AUD/month for accounting fees, then $400/year for incorporation fees, and 30% tax fees, is not beneficial - especially when we only brought in about $600AUD last quarter from Prismatik donations - just enough to cover our accounting fees but not anything else.

The shutdown will mean that copyright will move from Bevry Pty Ltd back to myself (Benjamin Arthur Lupton). This has increased risk for me if we ever violate a patent or IP law, however whatever, that's a risk that hopefully will never happen. It could also mean that if Bevry the community does bring in substantial money, then we can always re-register for tax reasons if it is strategic to do so. It also means that I will be receiving a lot of misplaced credit for our communities work, but I don't know any way around that, as undesirable for everyone that it is.

One option is that we get Apache or some other foundation to take ownership of everything.

Or we just find a good full-time accountant that can keep Bevry alive, without more fees than we take in.

## DocPad Plugin System Refactoring

There are two current issues with our plugin infrastructure that I'd like to address:

### Abstract out our Plugin APIs
Our amazing plugin infrastructure is DocPad specific. Other projects can't take it and run with it. Abstracting it out will be a huge benefit to the Node ecosystem - with many other projects wanting plugins, and us having the best system to date that I am aware of.

This would mean packaging up plugin loading, plugin installing, plugin finding, and plugin configuration handling, as well as the plugin event system, into it's own project(s), such that DocPad utilises that project, as well as any other projects wanting a plugin system can utilise that project too.

### Address Semantic Versioning via Registry Helper
Our plugin infrastructure currently links DocPad Major Versions to Plugin Major Versions. E.g. DocPad v6 compatible plugins should be v2. DocPad v5 compatible plugins should be v1. The reasoning for this is that it easily allows us to install versions of plugins that we know are compatible with our current docpad version. For instance when DocPad v7 comes out and with the current system, that means it would use v3 plugins. Then when we run `docpad install less` in DocPad v6, it will still install the latest compatible DocPad v6 plugin by doing `npm install --save docpad-plugin-less@2`. Makes sense.

The issue with this however, is that it ties version numbers to plugin compatibility. For DocPad's 6 major versions, this is how it worked - a major version was bumped when it would break compatibility in a major way - for instance, plugin API breaks. This has worked well for those 6 major versions and the previous 4 years.

However, now that the Node ecosystem has evolved from where it was at Node v0.4 when we first started DocPad (and when there were other package managers for node other than npm), it now makes sense to move past this now-limitation.

With npm, it will now install peer-dependencies if a peer-dependency is missing, however npm doesn't like peer dependencies, as no one can agree on how they should work. We at times have tried to depend on peer deps however the constant flux of their behaviour has been a stemming of issues for us.

Instead, we will expand our DocPad Helper Service (docpad/helper) to also facilitate registry handling. What this means is that in a very basic notion, every hour or so, the DocPad Helper Service will poll the npm registry for all packages matching the `docpad-plugin` keyword. It will then through the `docpad` peer dependency entry that is inside each DocPad plugin, build a database of which plugins are compatible with which DocPad versions. Then when DocPad goes to install a plugin, it will then poll our helper, find out the latest compatible version for its version, and install it. This will also allow DocPad to also gain commands like `docpad list plugins` to get an interactive listing of all the plugins available.

This is a very basic explanation of how it should work, but as a high level, it could simply be a way of indexing npm registry entries by their peer dep values, then be able to query that index so those peer deps can find out which plugins are available for it - it wouldn't be DocPad specific, but anything.

That is the registry abstraction that would take place, which wouldn't depend on our actual plugin APIs of the first part.

## Strengthen Community Workflows
During my absence of 2014, the DocPad community stagnated a bit to my surprise. I had though I had developed good workflows, but alas while they are good, they could be a lot better. The io.js project has certainly shown us all what a great workflow can become.

### Automated Permission Granting
This will mean automating the distribution of permissions and maintenance rights of all our official plugins to the DocPad extras team with push access, and to our DocPad core team with publish access. This means if a plugin now becomes an official one, the appropriate teams automatically get push and publish access without me having to do it manually.

While that will help people who know what needs to be doing, it won't help people who don't know what needs to be doing.

### Contribute Control Centre
It's disappointing that we have more than 1 page of pull requests for both Bevry and DocPad still open, with some more than a year old. This shouldn't happen - but it has only happened because knowledge of these pull requests isn't distributed in a way where it becomes actionable.

We will have to add a contribute control centre to our Bevry Website where anyone who wants to contribute can see who is on the appropriate teams, see all the open pull requests, see all the issues that need pull requests, and see the raging discussions forums.

### Discussion Forums
Currently GitHub is the big discussion forum for everything. We've tried to make this possible relentlessly, but it doesn't seem to have worked that well in hindsight when we compare it to say Atom Editor.

Atom's use of a dedicated forum for all topics that aren't specifically related to an actionable task is very good for it. The big issue with our current github system is that you always need to know which repo's issues you want to go to - making the breadth of knowledge you must have just to submit an issue in the right place impossible. Having a dedicated forum for DocPad will help with that.

 

## Strengthen the DocPad/Bevry Business
Ghost and npm inc. showed us all what is possible within the node ecosystem of having a good business model. DocPad's business model was to become the WordPress of Node, but in hindsight that failed for now obvious reasons. When DocPad's sponsorships were dropped in March 2014, we had no money to sustain the development, with myself in a really bad place. DocPad is a huge ecosystem, that demands full time attention.

### Serious about Trainings
We need to get more serious about trainings. We currently have http://learn.bevry.me but for various reasons, it needs to do better. We need suggestions and outside help here. For instance, there is a "Hands on with Node" training in our learning centre, but I'd suspect that 99.9% of our community has even heard of it. We need to get serious about training and knowledge sharing, from a business perspective, as well as from a burnout perspective. If the only person who knows something drops out, that is a problem. We must share our knowledge to ensure other people can glide on gracefully if we leave.

### Serious about Sponsorship
Currently most sponsorship deals have gone to Bevry, when I am in a state of mind to receive them. Now that I am feeling better, it's time to make all the above happen. That will require significant funds to fund the work involved. Currently nearly everything is locked up into my brain, and I need to spend the next 6 months getting it all out of my brain, so if I go hermit again, the community is fine.

This will mean initially receiving funding for Bevry and then afterwards through the development of the new infrastructure, getting serious about sponsoring our extended community too. Currently we have our Support Partners section, but we really need to somehow empower our teams more, rather than just companies.

This means sponsorship for dedicated development, sponsorship for specific development, and sponsorship for support etc. We need to be a lot clearer about our business model, and more empowering to let people give us their money.

## New Websites
Naturally the above means that new websites are due. At this point, let's just look for designs for this. They need to be way simpler, and way cleaner. If there are any designers, let's get that rolling.

## Get a Marketing Presence
As a long-shot, it would be great if we got some marketers onboard to handle our non-existant blog initiative, as well as our social media accounts, company relations, etc.

## So what now?
So Bevry needs about $20,000USD to accomplish the above over the next 6 months to tie up legal and accounting costs, as well as ensure I have some money to cover my costs while I develop stuff. If we get more, even better, it will help further things on, and perhaps if we get enough I can allocate some towards other developers too, rather than it just going in a trust for future Bevry expenses (like domains, hosting, etc etc).

Doing the above pitches up as a crowd-funding campaign would probably be the way to go, unless some sugar guardian can provide for it beforehand.

This is a very important thing, that would be cool if we got community involvement on.

## And me?
As some people may have noticed, I pretty much had a breakdown last year. All our sponsors dropped, and I had no work offers that wouldn't mean assigning all my open-source IP to the company I work for. I lost interest in programming, and pursued other interests such as sustainable and simple living. I have 6 months to tie up my university commitments, which with enough raised funding will mean we get this roadmap completed in those 6 months too. When I finish uni, I plan to do the [Bibbulmum Track](https://www.bibbulmuntrack.org.au/) by myself aiming to not spend any money, so foraging and dumpster diving for food. If that is a success, then it is further points for my [travelling from Australia to England only spending money where legally required](https://gitlab.com/balupton/sydney-to-london-moneyless/wikis/home) idea. Either way, after the Track, I will revaluate things. My current interests are still no longer with programming to whatever degree, but with sustainable living. Perhaps that means a job at Tesla, perhaps that means a Hermit in the Woods, perhaps it means hitchiking around the world with a blog, perhaps it means helping vegan businesses with my IT skills, perhaps it means staying a part of the Bevry business, I don't know at this point, and will be closer to that answer at the end of the year.

**Comment by ahdinosaur** [comment]
:+1:

**Comment by SteveMcArthur** [comment]
Thanks for your insights and plans. Sounds like you've got a fantastic year ahead of you. Nothing like the Australian bush in the world for peace in perspective. Oh my god! Not another Aussie backpacker in London! That was me a long while ago - and I didn't leave! :)

**Comment by balupton** [comment]
;-P

**Comment by alexwoehr** [comment]
When you mentioned just the Prismatic donations, I wondered what DocPad
brought in on Gratipay...unfortunately not very much. Too few people give
to open source! :-(

**Comment by balupton** [comment]
@alexwoehr yeah it's funny, the documentation browser Dash earns like 350,000USD a year, whereas the much better and open-source and free one DevDocs earns less than $30USD a week. Very sad.

**Comment by Zearin** [comment]
@balupton: For the past several months I was finishing up my own university courses, and I completely missed the turmoil you’ve described here.  I’m sorry it’s been so difficult.  But know that I used DocPad to build my senior project to complete my Web Communications degree, and I really respect it as a phenomenal piece of software that I plan to continue using for a long time.  You’ve set a great thing in motion with all of this.

Regardless of what you decide for your future, I wish you the best of luck.  May you find happiness and satisfaction in whatever path you walk.  

If that path ends up including programming in any degree, then…May The Source be With You!  

If not, then…Whatever You Are, Be A Good One.  

Take care, Benjamin!

**Comment by derberg** [comment]
@balupton  I think that such a honesty and openness you share here is remarkable and I respect you a lot because of it!

I'd like to share some of my thoughts about DocPad, hope you don't mind.

## Promotion
I think that the main promotion part should focus on saying that DocPad is capable of something more than blog platform or in general - site generator. The biggest popularity belongs to jekyll and I think that it is only because of its presence on GitHub pages. People do not realise there is something more than jekyll. Therefor DocPad should focus into 2 topics:
* Be promoted as a tool to build documentation portals. Development market is blowing up with REST APIs popularity, mainly because of the cloud popularity: http://www.programmableweb.com/ This means thousands different APIs need to be documented each year. They need to be documented mostly by developers and there are not many technical writers with proper technical knowledge to do it. This mean technical people that don't want to use crappy wikis or other solutions. They want something easy and flexible. They want something that is a nice fit for small projects (https://github.com/devo-ps/carte) and for big API projects (like this one https://github.com/liferay/alloyui.com). This is why projects like http://readme.io/ or https://pages.github.com/ gain such a big popularity these days. I'm on my own trying to go that direction with docpad promotion with http://derberg.github.io/. I will also plan to join 3 big technical writing conferences in europe where I could promote docpad as a documentation tool. Maybe we could do it globally - or first see how I'm doing with it and see if that makes sense. 
* make it much more easy to start immediately a new project with docpad. The current skeletons are cool, but I think that they should be much cooler from UI design perspective. There are hundreds of free bootstrap templates for blogs and other kind of websites. I'm using this one for my blog: http://startbootstrap.com/template-overviews/clean-blog/ and I'm building a portfolio page for my godfather using this http://startbootstrap.com/template-overviews/freelancer/. Did you notice that both of these templates are available as jekyll projects? shouldn't there be also a DocPad version? Not github is floated with "docpad-plugin" projects, maybe there should be additional category called "docpad-themes" or something. Both jekyll samples I've described above and together 300likes on github - this is how you build popularity. I could transform my blog (https://github.com/derberg/blog-docpad-learn) to a first docpad theme as like I mentioned above, I've based it on clean blog template. Let me know what you think.

## Community
Recently I've got a bit disappointed by our community. I tried to find some solutions talking to people on docpad's official irc channels and gitter chat and I had no response. I think that if you promote some channels for support, they should be reliable. Idea for such communication channels is awesome - openness is what people seek for - but they need to be reliable. 

## Donation
I remember when I've sent you an info on june last year that my company will donate you. We fought with  approval process, then were blocked by budget processes, now trying to figure out how we can actually transfer the money out. I hope that we will make it before june :( the good thing is that once we go through that process and learn how to follow up - every year donations will be easy peasy. Maybe when it will be clear that SAP donates you, that will trigger others - I truly hope about it.

**Comment by mikeumus** [comment]
@derberg, great feedback and SAP, that's huge. Would definitely have a follow the leader effect.

**Comment by aoberoi** [comment]
@balupton i'm glad you've decided to spend more time to think about what you personally think is worthwhile. in the meantime, i'm grateful you've been spending more time on DocPad as I think its a brilliant project!

A question regarding the SemVer Registry Helper: Is the point of building this separate index to just sidestep the behavior of npm in the case that it changes? The functionality you describe sounds like work that the npm cli already does, and most likely belongs there. Perhaps I missed something.

**Comment by balupton** [comment]
@aoberoi the way npm handles it changed from v1 to v2, and then it will change again from v2 to v3.

v2 functionality:

- When installing a package that has missing peer dependencies, npm will install the missing peer deps
- When installing a package that has other dependencies you are using as peer deps, npm will try and install the latest version of that package, and then complain about peer dep incompatibilities if there are any

v3 functionality:

- npm will no longer install missing peer deps
- When installing a package that has other dependencies you are using as peer deps, npm will behave like npm v2


Example problem is when we upgrade DocPad to v7 and some plugins, if people are still using DocPad v6, `npm install docpad-plugin-blah` will install the latest blah version (which would be for DocPad v7) and then complain about an incompatibility. What we need, and what the proposed service will do, is allow us to install the appropriate version of the blah plugin package that is compatible with our dependencies.

**Comment by aoberoi** [comment]
@balupton thanks for the detailed explanation, that was very helpful.

i've just spent a few hours reading through various discussions in npm/npm about what should be done with the future of peerDependencies. its a tough problem. i'm sure you've given more thought to this than i have, but i have one novel idea that i hadn't heard proposed yet.

i think it might be a mistake to overload the major version number in semver to also semantically mean "this is the backwards compatible plugin API version". strictly speaking as npm interprets it, the major version represents the backwards compatible `require()` API of the module. but plugins don't necessarily `require()` the thing they plug into, they expect the top level application to `require()` it.

here's the idea: since these are 2 different things, i think they ought to be stored separately. perhaps it could be a new field in package.json for the plugins (`docpadPluginAPIDependency`) that is also formatted as a semver string. docpad (the plugin host) could expose a new field (`pluginAPIVersion`) that is also formatted as a semver string. this would successfully decouple the plugin API's versioning from the plugin host itself.

this doesn't solve the problem of getting the application to a runnable state right after an `npm install`. maybe there's a way to utilize the "postinstall" script hook in the docpad module to traverse the dependencies and make sure they are all plugin-compatible. if not, it can use semver against the `docpadPluginAPIDependency` values across the dependency graph to resolve which `pluginAPIVersion` would work in this combination of plugins and then error out to the user with that as a suggestion.

to be honest, in the instance of docpad this is an overengineered solution (using the major version and indexing by that on an external service is functionally equivalent). i was trying to think of a model that could apply to the general node ecosystem to help overcome the deficiencies of peerDependencies. i thought i might bring it up here as a means to explore if we could advance the state of solutions to plugin ecosystem problems. i see this as an opportunity to try something new and if it works it could prove the feasibility for others plugin ecosystems to adopt. perhaps this work belongs in a separate module that does general plugin resolution.

PS. the names i chose look ugly, just trying to illustrate a point.

**Comment by balupton** [comment]
@aoberoi yep, the smaller and more decoupled the dependencies, the more precision authors will have for specifying their compatibilities - no need to specify `pluginAPIVersion`, instead they can just do `peerDependencies.plugin-engine-loader: ^1.0.0`

**Comment by balupton** [comment]
@aoberoi some more thoughts at https://discuss.bevry.me/t/docpad-architecture-vision-2015/46

**Comment by aoberoi** [comment]
> pluginAPIVersion would be switched to peerDependencies.plugin-engine-loader: ^1.0.0 - if a DocPad plugin depends on the file system, then peerDependencies.docpad-plugin-fs: ^1.0.0

My suggestion is to circumvent `peerDependencies` all together, and possibly add the desired install behavior via npm's script hooks.
