### ISSUE TITLE
Remove "The plugin is using uncompiled CoffeeScript files" for local plugins

### ISSUE THREAD

**Issue by dimitarkolev** [docpad/docpad#928]
I have a lot of local plugins that are not compiled, and I dont want to compile them. I don't intend to publish them no npm either. They are project specific and can't be reused. This warning is very annoying. Is there docpad.coffee configuration to block it? Or even better don't show it by default for local plugins, because there is not added value of having such a restriction for your local plugins.

**Comment by balupton** [comment]
I'll add an option to disable the warning for local plugins.

**Comment by balupton** [comment]
Added the ability to turn off warnings about uncompiled private plugins. So uncompiled plugins that have `"private": true` inside their `package.json` files.

I did this instead of local plugins, as in the end, all the plugins are local, so it would be a lot harder check to get right, than the `"private": true` check.
