### ISSUE TITLE
documentation for creating and testing docpad plugins needs to talk about how to simulate project configuration.

### ISSUE THREAD

**Issue by airtonix** [docpad/docpad#941]
When testing a docpad plugin you want to have at least two sets of configuration: the defaults that the plugin creates itself, and a mock configuration that lives alongside the test project.

No where in the (sparse)documentation for testing your custom plugins was it mentioned how and where you would provide a simulated configuration for the test project.

Until I happened across this post :
http://www.delarre.net/posts/unit-testing-docpad-plugins/

There needs to be some talk about being able to supplying mock docpad project configuration as an attribute of the test class.

**Comment by SteveMcArthur** [comment]
Yep - testing seems to be a problem with docpad. I would like to test my plugins in isolation which by definition is stupid since of course you need docpad. I've considered writing a plugin whose only purpose was to test other plugins. I've actually been bitten a couple of times by writing plugins without a decent testing regime. One thing I've found is that you need to test for no configuration - ie the user has installed the plugin but then forgotten about it.

**Comment by balupton** [comment]
Until we have proper docs, see the tests for:

- https://github.com/docpad/docpad-plugin-cleanurls
- https://github.com/docpad/docpad-plugin-paged

**Comment by SteveMcArthur** [comment]
@balupton Thanks - the cleanurls tests have helped me a lot in designing tests for my own plugin. Good example of supplying mock configuration. This is what I was looking for.

**Comment by balupton** [comment]
Closing due to age
