### ISSUE TITLE
README.md: bitcoin donate badge is broken

### ISSUE THREAD

**Issue by alexwoehr** [docpad/docpad#946]
bitcoin donate badge links to a page that says, "This item is no longer available."

- Operating System: Linux (Fedora 20)
- Browser: Chrome 41

**Screenshot of badge that is broken**

![image](https://cloud.githubusercontent.com/assets/716137/7172275/d04a1e86-e3b2-11e4-95f2-25614d296e28.png)

**Screenshot of linked page**

- URL: https://www.coinbase.com/checkouts/9ef59f5479eec1d97d63382c9ebcb93a

![image](https://cloud.githubusercontent.com/assets/716137/7172288/06faa928-e3b3-11e4-9051-1d9763a5c0b1.png)

**Comment by balupton** [comment]
Strange....

**Comment by balupton** [comment]
Got access to coinbase. They now need to verify the details of merchants, which is now completed.

The old URL will still work, however we should update the urls to more robust ones.

Fixed with https://github.com/docpad/docpad/commit/2ec0ae7265b31c3e462c04afc462b429324cddfe

However needs a projectz rebuild. This will happen on the next release.

Closing for now :-)
