### ISSUE TITLE
Performance research

### ISSUE THREAD

**Issue by dimitarkolev** [docpad/docpad#994]
Because of the poor performance of DocPad we have decided to investigate if its possible to come up with a prototype of a system that is compatible with DocPad in terms of documents, layouts, collections and paging as well as cross document reference when rendering. 
The tests were performed against a real life site with 3000 documents and 20 layouts with 5 of them using paging on a i7 laptop with 4 cores and 4GB of RAM. After several iterations this is what we have found out. 
1. We decided to store the documents in a JavaScript database. We used PouchDB. This solution took 10 minutes to render compared to a 1.5 hours for DocPad which is significant boos but still not fast enough.
2. We changed the database from PouchDB to MongoDB and the same setup took less than a minute to render.
3. As well as using a database we did another change. We decided to go multi thread. So we used nodejs clustering  for document rendering. Using this approach we can utilize the full CPU power. Testing on a server system with 24 cores and 4 disk RAID drops render time to about 10 sec.
4. We also implemented document version checking so we don't render documents that has not been changed (we track cross document references as well) so when you save a document and regenerate the whole site it feels almost instant. But this was not used in the tests above.

Our conclusion is that the main bottleneck for DocPad performance is so called QueryEngine which just cant compare to a real database. Second thing is the fact that DocPad is using only one core for rendering but it will be much harder to change, I think.

Our implementation has not even 10% of the features DocPad has, but it happened to have 95% of the features that we were using. Its just a prototype that renders documents very fast and the code is mess, but it proves that DocPad can be a much faster system without sacrificing a lot of features.

**Comment by balupton** [comment]
This is not news to anyone. The problem is DocPad has no resources to improve on any of this. I've been contemplating moving to PouchDB for the database for the last year, and have a good system and roadmap planned out, but until people want to pay up, it won't get done — there's nothing worthwhile in it for me to invest 6+ months of development in a new version of DocPad for free, working for free it making you homeless sucks. The funny thing is, multiple companies are all happy to pay their own employees to experiment with the exact same thing, causing redundant efforts, versus them just paying an outsider of their company, the person actually making the tool they use, to fix it once and for all for everyone.

**Comment by dimitarkolev** [comment]
Pouch is very slow compared to Mongo and the transparent migration from Pouch to Couch is a version mess and far from a production ready solution. We can't recommend it.

We spend months optimizing our work-flow (even forked several plugins) with DocPad and we continue to use it for our projects but every time we asked about performance there was only misleading information and even denial that DocPad is slow at all. So we invested less than a month of development just to verify what the speed gain of a re-designed system will be. Our research was motivated from the threads here which contained no real reasoning for DocPad being slow nor any real feedback how fast it can be. We tried several other static site generators and can't say they offer better performance with the same set of features as DocPad. So we deicided to spend few weeks to play with node and see what we can do.
We don't want to recreate DocPad, but we are planning to execute projects with thousands of documents and we were looking for an answer if a static site generator can help us doing so.

As for the payment to an outsider helping him develop the tools that we use - We can't pay without any proof of concept. There was no real commitment about the reimplementation of DocPad with performance in mind. You said there are several companies but I never saw an effort to spread the expenses between them and reach an amount that we can handle. And last but not least the average payment here is 10 times less than Australia which means that its almost impossible for us to finance a serious portion from such a project. Don't know about other companies and their reasoning.

We just wanted to share some real numbers from our research that was missing in any roadmap I have seen.

**Comment by balupton** [comment]
> We spend months optimizing our work-flow (even forked several plugins) with DocPad and we continue to use it for our projects but every time we asked about performance there was only misleading information and even denial that DocPad is slow at all. So we invested less than a month of development just to verify what the speed gain of a re-designed system will be. Our research was motivated from the threads here which contained no real reasoning for DocPad being slow nor any real feedback how fast it can be. We tried several other static site generators and can't say they offer better performance with the same set of features as DocPad. So we deicided to spend few weeks to play with node and see what we can do. We don't want to recreate DocPad, but we are planning to execute projects with thousands of documents and we were looking for an answer if a static site generator can help us doing so.

There's several unique issues with the performance of DocPad, and several issues that are common amongst SSGs in general. Documenting this takes a lot of time. Publishing a roadmap takes a lot of time. Our last sponsor dropped out in March 2014. Since then, DocPad has been completely without funding - investing more time into it would be at complete loss. No one has come forth since about any interest in funding anything. We currently make $2/week on Gratipay, that's all the income I've received this year. This year, I have been homeless and without computer access, I have regained those. It's hard to justify investing a lot more time, or any further time that matter, into something that can't manage more than $2/week, with no indication that will ever change.

I'm not blaming you, companies, or anyone in particular — no one is to blame, if anyone is to blame, it is me for not stabilising a business model for DocPad the past 2 years, and leaving me broke. The intention of the initial post I had was to just state what the underlying problem is. The underlying problem is not that DocPad is slow, it is, the problem is DocPad can't not be slow without funded developers working on making it faster, and that can't happen until ... — well that is the question!

It's a chicken and egg problem perhaps. You want guarantees we will deliver. We can't provide guarantees without guarantees of funds. I don't know what the solution is... I'm trying to figure that out. It's the elephant in the room, and needs to be discussed. Sorry if for coming across as an arse, I'm not sure how to discuss the elephant in the room without coming across as an arse.

**Comment by dimitarkolev** [comment]
I tend to threat most of the open source projects as side projects. I see that you want DocPad to become a sustainable business but from what I saw its very big leap to do. You know my love about the project and your work, but making such a project profitable by its own is very hard and usually can take more time than your bank account can.
I love DocPad and its concept of staying out of the way and I want it to be best of the best no matter what is your financial situation. I don't think open source has anything to do with financial situations and profit, they are more like a side effect of the work and passion.
I believe DocPad should never stop improving unless as you once said you lost interest in the field.

**Comment by balupton** [comment]
> I tend to treat most of the open source projects as side projects. I see that you want DocPad to become a sustainable business but from what I saw its very big leap to do. You know my love about the project and your work, but making such a project profitable by its own is very hard and usually can take more time than your bank account can.
> I love DocPad and its concept of staying out of the way and I want it to be best of the best no matter what is your financial situation. I don't think open source has anything to do with financial situations and profit, they are more like a side effect of the work and passion.
> I believe DocPad should never stop improving unless as you once said you lost interest in the field.

A side-project is something for one's self. DocPad meets my performance needs.

There are several things on DocPad's todo:

- Convert everything to ES6+ (this will speed everything up by at least 1/4) - this is 2-3 months work
- Document each project way better - this is invariable amount of work
- Publish guides on improving DocPad's current performance - this is 1 weeks work
- Improve DocPad's performance with existing infrastructure - this is 3 weeks work
- Work on new database system that will enhance DocPad - this is 2 months or so of work
- Abstract out the core into several plugins, including the plugin system itself - this is 1 month of work
Improving DocPad's performance

These are all full-time efforts. Doing this for free is crazy talk, and how I ended up broke.

Company-driven OSS is fine, as the companies fund the development of this. React, Angular, Polymer are examples of this - they are loss-leaders for things that bring in income (other products, free talent training and appeal). The problem is companies expect all OSS software to be like this, Community-driven OSS isn't, it depends on funding by companies - and companies are shocked by this, thinking - hey this is just a side-project, you pay for our requests, not us!

It drives me mad. https://blog.bevry.me/changes-to-bevry-d1e0bd218ccb?source=latest

**Comment by balupton** [comment]
It's pretty late here, so going to go to bed. Would you like to do a call sometime? Would be great to discuss this in a more conducive medium.

**Comment by dimitarkolev** [comment]
I think its much more simpler than that. Someone needs a solution for a task. He looks for ready to use open source solution. If he can't find one - he builds one. Other people find it useful and start to use it and give ideas for improvement. If the author likes them he incorporates them into his project if not, he don't. It people insist on those things being part of the project they fork the project and add them into their fork and ask the author for a merge. If they can't implement them because they lack knowledge or understating they start looking for another solution which might be another project that has this features or they decide to do it from scratch by themselves based on the experience they have with the project they used and its source and ideas as a reference. They publish this project and it goes again through this loop again and again. If a project becomes vital for many people and companies it might end being profitable but its takes more than just time to do so. I don’t think someone is treating OS as a free external workforce this is the whole concept behind it - everyone benefits from the efforts of the others without profit being part of the equation. 
P.S. You have my skype I am always ready for a chat.

**Comment by balupton** [comment]
> I think its much more simpler than that. Someone needs a solution for a task. He looks for ready to use open source solution. If he can't find one - he builds one. Other people find it useful and start to use it and give ideas for improvement. If the author likes them he incorporates them into his project if not, he don't. It people insist on those things being part of the project they fork the project and add them into their fork and ask the author for a merge. If they can't implement them because they lack knowledge or understating they start looking for another solution which might be another project that has this features or they decide to do it from scratch by themselves based on the experience they have with the project they used and its source and ideas as a reference. They publish this project and it goes again through this loop again and again. If a project becomes vital for many people and companies it might end being profitable but its takes more than just time to do so. I don’t think someone is treating OS as a free external workforce this is the whole concept behind it - everyone benefits from the efforts of the others without profit being part of the equation.

Very similar summation that [my recent tweets](https://twitter.com/balupton) entail too - definitely a lot of redundancy in need of a better solution.

> P.S. You have my skype I am always ready for a chat.

Cool, will reach out tomorrow.

**Comment by balupton** [comment]
@dimitarkolev I've created https://github.com/bevry/readdir-cluster as a first step to adding clusters to DocPad

**Comment by balupton** [comment]
The docpad versions since 6.80 and up solve this more or less
